name: Large File Sharing
favicon: null
layout_spectrum: 0.3301
typography_spectrum: 0.47902
title: Large File Sharing
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: pub-1427543002106375
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#222222'
    - '#ffffff'
    - '#8d8d8d'
    - '#cfcfcf'
    - '#cea20d'
  brandStrength: 0.1875
  lightness: 0.12016107141971588
  saturation: 0.3382877823896706
  rhythmicContrast: 0.3540431265719235
purpose: []
