name: Large File Sharing
favicon: null
layout_spectrum: 0.22215816983953118
typography_spectrum: 0.6134395617991686
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.2732099862769246
  lightness: 0.12016107141971588
  saturation: 0.3382877823896706
  rhythmicContrast: 0.3540431265719235
purpose: []
