name: Large File Sharing
favicon: null
layout_spectrum: 0.3301
typography_spectrum: 0.47902
title: Large File Sharing
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: pub-1427543002106375
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0f0f0f'
    - '#767475'
    - '#c62827'
    - '#88bb54'
    - '#fefefe'
  brandStrength: 1
  lightness: 0
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
